### ISSUE TITLE
Sync Issues

### ISSUE THREAD

**Issue by betterbydesign** [StormSDK/StormApp#1]
I noticed I have a bunch of files in my desktop Storm folder that aren't showing up in my MacBook storm folder. I tried quitting and reopening but it did not trigger syncing. How can I do this manually?

Also I noticed whenever I restart my computer I get two identical Storm icons that show up. I usually quit one of them,: could this be the issue?

**Comment by payne8** [comment]
Hey @Satori83 sorry I have been MIA. I have released a [new version](https://github.com/StormSDK/StormApp/releases/tag/v0.3.9) that addresses (hopefully) the issues you were seeing. I especially hope it fixes the double app problem. 

If it doesn't fix the double app problem right away try turning off and on the "Run at start-up" option in the preferences window.

Let me know if you are still seeing issues with the latest update. Thanks so much for trying it out!
